### ISSUE TITLE
[Refactor] Aggregate and repository

### ISSUE THREAD

**Issue by lzukowski** [Enforcer/python-event-sourcery#14]
1. Aggregate operates on Aggregate Events without any persistency information (version, uid, date, etc)
2. Repository is responsible for reading persisted Events and converting them into Aggregate Event
3. Repository is responsible for converting Aggregate events into persistency events. Adding enrichment (id, version, created_at, etc)
4. Change RawEventDict with Protocol representing Persistency Event in EventStore
5. Basic EventStore will work on Persistency Event Protocol, and wont map it with EventRegistry (moving to Repository)
6. Introduce EventStore with additional functionality of mapping persistency Events with EventRegistry

**Comment by Enforcer** [comment]
Implemented various changes
