### ISSUE TITLE
Repackage

### ISSUE THREAD

**Issue by lzukowski** [Enforcer/python-event-sourcery#21]
From technical packaging (interfaces, dto, etc.) into patterns (Read Model, DDD, Aggregate root, etc).

**Comment by chkoar** [comment]
Right now the dependencies of esdb, kombu and sqlalchemy are installed by default, right? If this is the case they could be placed under the ‘event_sourcery.contrib’ package like in many other libraries. If the case is to have them with optional dependencies or better to split them in the future I understand.

**Comment by lzukowski** [comment]
Hi. You are right about managing these packages. We will change them and make backend implementations as separate distributed packages.

The goal of this task was to reorganize code into a more meaningful structure.
