### ISSUE TITLE
Outbox with contextmanager

### ISSUE THREAD

**Issue by lzukowski** [Enforcer/python-event-sourcery#23]

**Comment by lzukowski** [comment]
Use context manager, so storage strategy can decide when to commit outbox updates from reader.

**Comment by Enforcer** [comment]
Like this?
```python
outbox = event_store.outbox()
with outbox.entries() as entries:
    for entry in entries:
        publish(entry)
# on __exit__, `entries()` marks events as sent

```

**Comment by Enforcer** [comment]
What are then benefits over `Outbox.run_once`? That we don't have to pass publisher and we can do it explicitly instead?
